# Generated by Django 4.2.27 on 2026-01-28 13:25

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Management",
                "permissions": (
                    (
                        "access_permission_management",
                        "Can access the Permission Management module and manage permissions",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
